"""Workspace conversion README — one document covering every converted program.

Contract: docs/LOCAL_DEPLOYMENT_WORKFLOW.md (additive per CONTRACTS §0).
Owner: P3 (tool), P1 (route).

The documenter agent (§10) documents one program per job. This assembles those
per-job reports into the document a maintainer actually needs when they open the
output folder for the first time: what was converted, what each generated method
does and which COBOL paragraph it came from, how the programs depend on each
other, and what still needs a human.

Deterministic on purpose — it is a projection of data the agents already
produced, so it renders identically with the LLM down.
"""

from __future__ import annotations

import time
from typing import Any, Dict, List

from .registry import tool

__all__ = ["render_conversion_readme"]

_SEVERITY_ORDER = ("error", "warning", "info")


def _escape_cell(value: Any) -> str:
    """Table cells are pipe-delimited, so a pipe in the data has to be escaped."""
    return str(value if value is not None else "").replace("|", "\\|").replace("\n", " ")


def _table(headers: List[str], rows: List[List[Any]]) -> List[str]:
    if not rows:
        return []
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(_escape_cell(c) for c in row) + " |" for row in rows]
    return out


def _program_section(program: Dict[str, Any]) -> List[str]:
    name = program.get("program_id") or program.get("filename") or "UNKNOWN"
    lines = [f"## {name} → `{program.get('class_name', '')}.java`", ""]

    source = program.get("source_path") or program.get("filename")
    meta = [f"**Source:** `{source}`"] if source else []
    if program.get("status"):
        meta.append(f"**Status:** {program['status'].replace('_', ' ')}")
    counts = program.get("finding_counts") or {}
    if any(counts.get(s) for s in _SEVERITY_ORDER):
        meta.append(
            "**Findings:** "
            + ", ".join(f"{counts.get(s, 0)} {s}" for s in _SEVERITY_ORDER if counts.get(s))
        )
    if program.get("used_fallback"):
        meta.append("**Generated by:** deterministic skeleton (LLM unavailable)")
    if meta:
        lines += [" · ".join(meta), ""]

    summary = _javadoc_prose(program.get("class_javadoc"))
    if summary:
        lines += [summary, ""]

    methods = program.get("methods") or []
    if methods:
        lines += ["### Methods", ""]
        lines += _table(
            ["Method", "From COBOL", "What it does"],
            [
                [f"`{m.get('java_name', '')}`",
                 f"`{m['cobol_paragraph']}`" if m.get("cobol_paragraph") else "—",
                 m.get("purpose", "")]
                for m in methods
            ],
        )
        lines.append("")

    variables = program.get("variable_map") or []
    if variables:
        lines += ["### Field mapping", ""]
        lines += _table(
            ["COBOL", "PIC", "USAGE", "Java", "Type", "Note"],
            [
                [v.get("cobol_name", ""), f"`{v.get('pic', '')}`", v.get("usage", ""),
                 f"`{v.get('java_name', '')}`", f"`{v.get('java_type', '')}`", v.get("note", "")]
                for v in variables
            ],
        )
        lines.append("")

    notes = program.get("migration_notes") or []
    if notes:
        lines += ["### Migration notes", ""] + [f"- {n}" for n in notes] + [""]

    unsupported = program.get("unsupported") or []
    if unsupported:
        lines += ["### Needs a human", ""]
        lines += [
            f"- **{u.get('feature', '')}** ({u.get('count', 0)}) — {u.get('detail', '')}"
            for u in unsupported
        ]
        lines.append("")

    return lines


def _javadoc_prose(javadoc: Any) -> str:
    """The Javadoc block as plain prose — comment syntax reads badly in a README."""
    if not javadoc:
        return ""
    text = str(javadoc).replace("/**", "").replace("*/", "")
    lines = [ln.strip().lstrip("*").strip() for ln in text.splitlines()]
    return " ".join(ln for ln in lines if ln and not ln.startswith("@")).strip()


def _dependency_section(dependencies: Dict[str, Any]) -> List[str]:
    """Cross-file dependencies, from the same scan that draws the workspace graph."""
    edges = dependencies.get("edges") or []
    nodes = {n.get("id"): n for n in dependencies.get("nodes") or []}
    if not edges:
        return []

    def label(node_id: str) -> str:
        node = nodes.get(node_id) or {}
        return node.get("label") or node_id.split(":", 1)[-1]

    kinds = {
        "call": ("Program calls", "Calls"),
        "copy": ("Copybooks", "Includes"),
        "sql": ("DB2 tables", "Reads/writes"),
        "file": ("Datasets", "I/O"),
    }
    lines = [
        "## How the programs fit together",
        "",
        "Every COBOL file in the workspace, including any not converted in this run.",
        "",
    ]
    for kind, (heading, verb) in kinds.items():
        # Two files can carry the same PROGRAM-ID, which makes their edges
        # indistinguishable once rendered by label — collapse the duplicates.
        rows: List[List[str]] = []
        seen: set[tuple[str, str]] = set()
        for e in edges:
            if e.get("kind") != kind:
                continue
            row = (label(e["from"]), label(e["to"]))
            if row in seen:
                continue
            seen.add(row)
            rows.append([row[0], verb, row[1]])
        if not rows:
            continue
        lines += [f"### {heading}", "", *_table(["From", verb, "To"], rows), ""]

    missing = [
        n for n in dependencies.get("nodes") or []
        if n.get("kind") in ("missing_copybook", "missing_program")
    ]
    if missing:
        lines += [
            "### Not in the workspace",
            "",
            "Referenced but never found, so nothing could be generated for them:",
            "",
        ]
        lines += [f"- `{n.get('label', '')}` — {n.get('sublabel', '')}" for n in missing]
        lines.append("")
    return lines


@tool(
    name="render_conversion_readme",
    description="Assemble per-job documentation into one workspace conversion README",
)
def render_conversion_readme(programs: List[Dict[str, Any]],
                             dependencies: Dict[str, Any] | None = None,
                             title: str = "COBOL → Java conversion") -> Dict[str, Any]:
    generated_ts = time.time()
    method_count = sum(len(p.get("methods") or []) for p in programs)
    field_count = sum(len(p.get("variable_map") or []) for p in programs)
    needs_human = [u for p in programs for u in (p.get("unsupported") or [])]

    lines = [f"# {title}", ""]
    lines += [
        f"{len(programs)} program{'' if len(programs) == 1 else 's'} converted · "
        f"{method_count} method{'' if method_count == 1 else 's'} · "
        f"{field_count} field{'' if field_count == 1 else 's'} mapped",
        "",
        "Generated by DeCOBOL. Every method below is traced to the COBOL paragraph "
        "it came from; anything the converter could not resolve is listed under "
        "**Needs a human**.",
        "",
    ]

    if programs:
        lines += ["## Contents", ""]
        lines += [
            f"- [{p.get('program_id') or p.get('filename')}]"
            f"(#{str(p.get('program_id') or p.get('filename') or '').lower().replace(' ', '-')})"
            f" — `{p.get('class_name', '')}.java`"
            for p in programs
        ]
        lines.append("")

    if dependencies:
        lines += _dependency_section(dependencies)

    for program in programs:
        lines += _program_section(program)

    if needs_human:
        lines += ["## Outstanding work across the workspace", ""]
        rolled: Dict[str, Dict[str, Any]] = {}
        for item in needs_human:
            entry = rolled.setdefault(
                item.get("feature", "Unknown"),
                {"count": 0, "detail": item.get("detail", "")},
            )
            entry["count"] += int(item.get("count", 0) or 0)
        lines += _table(
            ["Feature", "Occurrences", "Detail"],
            [[k, v["count"], v["detail"]] for k, v in sorted(rolled.items())],
        )
        lines.append("")

    return {
        "markdown": "\n".join(lines).rstrip() + "\n",
        "generated_ts": generated_ts,
        "program_count": len(programs),
        "method_count": method_count,
        "field_count": field_count,
    }
