/**
 * Generated by DeCOBOL from delete.cbl
 */
public class Dltpaypl {

    private String dltTimestamp = " ".repeat(26);

    public void run() {
        System.out.println("Dltpaypl executed successfully.");
    }

    public static void main(String[] args) {
        new Dltpaypl().run();
    }
}
