/**
 * Generated by DeCOBOL from read_update_v2.cbl
 */
public class Lndwise4 {

    private String wsOutfilePost = " ".repeat(80);
    private String wsSqlAction = " ".repeat(40);
    private int wsSqlcodeDisplay = 0;
    private Object wsCurrentDate = "";
    private String wsDateYyyy = " ".repeat(4);
    private String wsDateMm = " ".repeat(2);
    private String wsDateDd = " ".repeat(2);
    private String wsDateGenerated = " ".repeat(30);
    private String wsDateGeneratedLine = " ".repeat(50);
    private String wsDateForCalc = " ".repeat(10);
    private int currentLoanId = 0;
    private Object reportRecord = "";
    private int wsCustomerId = 0;
    private String filler = " ";
    private int wsLoanId = 0;
    private String filler2 = " ";
    private String wsLoanStatus = " ";
    private String filler3 = " ";
    private String wsNextPaymentStatus = " ".repeat(7);
    private String filler4 = " ";
    private String wsNextDueDate = " ".repeat(10);
    private String filler5 = " ";
    private BigDecimal wsPrevPaymentAmt = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private String filler6 = " ";
    private int wsPrevInvoiceId = 0;
    private String filler7 = " ";
    private String wsPrevDatePaid = " ".repeat(10);
    private String filler8 = " ";
    private BigDecimal excessAmtLoanCompletion = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private String filler9 = " ";
    private BigDecimal wsTotalInterestEarned = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private String statusOutfile1 = " ".repeat(2);
    private int wsReturnCode = 0;
    private BigDecimal leftoverPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal excessPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal excessLoanPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totExcessPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal wsPeriodDec = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private int currentInvoiceNumber = 0;
    private int numberOfInvoicesPaid = 0;
    private int wsNoInvoicesPaid = 0;
    private BigDecimal accumulatedTotPayments = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal adjustedMonthlyPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal monthlyInterestRate = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal remainingPrincipal = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal interestPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal principalPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalInterestPaid = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalPrincipalPaid = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalPaymentPaid = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalFullPayment = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalPaymentRemaining = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalPotentialAmount = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal actualMoneyToBank = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal totalExcessAmount = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private int wsDisplayNumber = 0;
    private String wsTestDisplay = " ".repeat(30);
    private int wsNullPaymentDate = 0;
    private int wsCounter = 0;

    public void run() {
        System.out.println("Lndwise4 executed successfully.");
    }

    public static void main(String[] args) {
        new Lndwise4().run();
    }
}
