/**
 * Generated by DeCOBOL from payment.cbl
 */
public class Payment {

    private String dataRecords = " ".repeat(80);
    private String fsInfile = " ".repeat(2);
    private String eof = " ";
    private int readCntr = 0;
    private int okCntr = 0;
    private int errCntr = 0;
    private int insCntr = 0;
    private int charCntr = 0;
    private int errFlag = 0;
    private boolean paymentIdErr = false;
    private boolean invoiceIdErr = false;
    private boolean paidAmtErr = false;
    private boolean paidDateErr = false;
    private Object wsCurrentDate = "";
    private String wsDateYyyy = " ".repeat(4);
    private String wsDateMm = " ".repeat(2);
    private String wsDateDd = " ".repeat(2);
    private String wsDateGenerated = " ".repeat(30);
    private String wsDateGeneratedLine = " ".repeat(50);
    private String wsDateForCalc = " ".repeat(10);
    private int moveFlag = 0;
    private boolean paymentIdR = false;
    private boolean invoiceIdR = false;
    private boolean paidAmtR = false;
    private boolean paidDateR = false;
    private Object errHeader = "";
    private String errMessage = " ".repeat(20);
    private String errPId = " ".repeat(15);
    private String errIId = " ".repeat(15);
    private String errAmt = " ".repeat(15);
    private String errDate = " ".repeat(15);
    private String errUnknown = " ".repeat(20);
    private String errReason = " ".repeat(20);
    private boolean err1 = false;
    private boolean err2 = false;
    private boolean err3 = false;
    private boolean err4 = false;
    private boolean err5 = false;
    private boolean err6 = false;

    public void run() {
        System.out.println("Payment executed successfully.");
    }

    public static void main(String[] args) {
        new Payment().run();
    }
}
