/**
 * Generated by DeCOBOL from create.cbl
 */
public class Wona {

    private int wsPaymentPeriod = 0;
    private BigDecimal wsMultiplier = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private BigDecimal wsInterestDecimal = BigDecimal.ZERO.setScale(4, RoundingMode.HALF_UP);
    private BigDecimal wsPrincipal = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private int wsCount = 0;
    private BigDecimal wsTotalLoan = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);
    private Object wsNumDate = "";
    private int wsNumYear = 0;
    private int wsNumMonth = 0;
    private int wsNumDay = 0;

    public void run() {
        System.out.println("Wona executed successfully.");
    }

    public static void main(String[] args) {
        new Wona().run();
    }
}
